name: Publish a Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      opensearch-version:
        description: 'OpenSearch Version to use'
        required: true
        default: 2.5.0
      ltrversion:
        description: 'LTR Plugin Version'
        required: true
        default: 2.1.0


jobs:
  build_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Set up Docker Buildx
      id: setup-docker-buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: docker/Dockerfile
        # TODO: fix this so it isn't hardcoded
        build-args: |
          opensearch_version=${{inputs.opensearch-version}}
          ltrversion=${{inputs.ltrversion}}
        push: true
        tags: gsingers/opensearch-learning-to-rank:${{inputs.ltrversion}}
        github-token: ${{ secrets.GITHUB_TOKEN }}